### ISSUE TITLE
Consul service not reachable. com.ecwid.consul.transport.TransportException: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by jhovell** [researchgate/archaius-consul#3]
If ConsulConfigurationSource has a problem initially connecting to one of the hosts, a cascading failure occurs where it will never connect to Consul and spew a high frequency error message to the logs.

First exception due to a server that has been terminated, just before a new application instance is launched (such as in a rolling hardware/instance update) (cause - UnknownHostException)

```
2016-05-04T20:32:52,662 ERROR [net.researchgate.archaius.ConsulConfigurationSource] [pollingConfigurationSource] Error while polling configuration. Try another server if available.: com.ecwid.consul.transport.TransportException: java.net.UnknownHostException: i-c2d9d21a.node.usw2.consul.: unknown error
    at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:80) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:39) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:81) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:150) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:143) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:133) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:384) [consul-api-1.1.7.jar:]
    at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:53) [archaius-consul-0.1.2.jar:]
    at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163) [archaius-core-0.7.3.jar:0.7.3]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_72-internal]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [rt.jar:1.8.0_72-internal]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_72-internal]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [rt.jar:1.8.0_72-internal]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_72-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_72-internal]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_72-internal]
Caused by: java.net.UnknownHostException: i-c2d9d21a.node.usw2.consul.: unknown error
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) [rt.jar:1.8.0_72-internal]
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) [rt.jar:1.8.0_72-internal]
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) [rt.jar:1.8.0_72-internal]
    at java.net.InetAddress.getAllByName0(InetAddress.java:1276) [rt.jar:1.8.0_72-internal]
    at java.net.InetAddress.getAllByName(InetAddress.java:1192) [rt.jar:1.8.0_72-internal]
    at java.net.InetAddress.getAllByName(InetAddress.java:1126) [rt.jar:1.8.0_72-internal]
    at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136) [httpclient-4.3.6.jar:4.3.6]
    at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:64) [consul-api-1.1.7.jar:]
    ... 15 more
```

This causes ConsulConfigurationSource to construct a "newClient" (line 81) which unfortunately uses the existing `private List<CatalogService> consulServices;` to base a connection from. But the service "consul" resolves to `consul-server-ip:8300` not `8500`. I think `CONSUL_SERVICE_NAME` should be `consul-agent-8500` for this logic to behave correctly

```
2016-05-04T19:04:29,435 ERROR [net.researchgate.archaius.ConsulConfigurationSource] [pollingConfigurationSource] Consul service not reachable. i-699d84ae: com.ecwid.consul.transport.TransportException: java.net.SocketException: Connection reset
    at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:80) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:39) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:81) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogService(CatalogConsulClient.java:129) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogService(CatalogConsulClient.java:122) [consul-api-1.1.7.jar:]
    at com.ecwid.consul.v1.ConsulClient.getCatalogService(ConsulClient.java:284) [consul-api-1.1.7.jar:]
    at net.researchgate.archaius.ConsulConfigurationSource.setClient(ConsulConfigurationSource.java:82) [archaius-consul-0.1.2.jar:]
    at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:66) [archaius-consul-0.1.2.jar:]
    at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163) [archaius-core-0.7.3.jar:0.7.3]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_72-internal]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [rt.jar:1.8.0_72-internal]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_72-internal]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [rt.jar:1.8.0_72-internal]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_72-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_72-internal]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_72-internal]
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:209) [rt.jar:1.8.0_72-internal]
    at java.net.SocketInputStream.read(SocketInputStream.java:141) [rt.jar:1.8.0_72-internal]
    at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160) [httpcore-4.3.3.jar:4.3.3]
    at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84) [httpcore-4.3.3.jar:4.3.3]
    at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273) [httpcore-4.3.3.jar:4.3.3]
    at org.apache.http.impl.conn.LoggingSessionInputBuffer.readLine(LoggingSessionInputBuffer.java:116) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260) [httpcore-4.3.3.jar:4.3.3]
    at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283) [httpcore-4.3.3.jar:4.3.3]
    at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271) [httpcore-4.3.3.jar:4.3.3]
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123) [httpcore-4.3.3.jar:4.3.3]
    at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) [httpclient-4.3.6.jar:4.3.6]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136) [httpclient-4.3.6.jar:4.3.6]
    at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:64) [consul-api-1.1.7.jar:]
```

Followed by 2 Apache http error messages:

```
Retrying request to {}->http://172.31.2.106:8300
I/O exception (java.net.SocketException) caught when processing request to {}->http://172.31.2.106:8300: Connection reset
```

Note ConsulConfigurationSource now thinks Consul resides on port 8300 and will no longer operate properly.

**Comment by jhovell** [comment]
I mistakenly thought this was a Consul API issue... more context here:

https://github.com/Ecwid/consul-api/issues/59

**Comment by jhovell** [comment]
also Consul documentation seems to corroborate port 8300 (on a Consul server) being the service associated with service "consul"

see 

```
dig @127.0.0.1 -p 8600 consul.service.consul SRV
```

https://www.consul.io/docs/agent/dns.html

**Comment by jhovell** [comment]
ok, I see from your readme you clearly want this library to search for other nodes of service type "consul":

https://github.com/researchgate/archaius-consul/blob/master/README.md

Also this page refers to service "consul" being on port 8300:

https://www.consul.io/docs/agent/http/catalog.html

Does your consul cluster really advertise the http api as service "consul"? I could create a pull request to (a) either make consul service name configurable or (b) simply change it to "consul-agent-8500" but I think that might break your use case.

Feedback?

**Comment by jhovell** [comment]
@Hillkorn any comment on this?

Forked this and updated the service name that my Consul agent uses & finding UnknownHostException can create even worse issues. Seems calling setClient() inside a catch block might be really risky.

This managed to fill my 8GB log volume in a few minutes... log looked like this with a stack trace every few milliseconds

```
2016-05-09T17:54:42,707 ERROR [net.researchgate.archaius.ConsulConfigurationSource] [pollingConfigurationSource] Error while polling configuration. Try another server if available.: com.ecwid.consul.transport.TransportException: java.net.UnknownHostException: i-40926986.node.usw2.consul.
        at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:80) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:39) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:81) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:150) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:143) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:133) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:384) [consul-api-1.1.7.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:53) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at net.researchgate.archaius.ConsulConfigurationSource.poll(ConsulConfigurationSource.java:67) [deltaspike-bouncycastle-archaius-1.0.0-20160506.200621-3.jar:]
        at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163) [archaius-core-0.7.3.jar:0.7.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [rt.jar:1.8.0_72-internal]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_72-internal]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [rt.jar:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_72-internal]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_72-internal]
Caused by: java.net.UnknownHostException: i-40926986.node.usw2.consul.
        at java.net.InetAddress.getAllByName0(InetAddress.java:1280) [rt.jar:1.8.0_72-internal]
        at java.net.InetAddress.getAllByName(InetAddress.java:1192) [rt.jar:1.8.0_72-internal]
        at java.net.InetAddress.getAllByName(InetAddress.java:1126) [rt.jar:1.8.0_72-internal]
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44) [httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259) [httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159) [httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304) [httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611) [httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446) [httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863) [httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) [httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214) [httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) [httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136) [httpclient-4.3.6.jar:4.3.6]
        at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:64) [consul-api-1.1.7.jar:]
        ... 47 more

2016-05-09T17:54:42,713 ERROR [net.researchgate.archaius.ConsulConfigurationSource] [pollingConfigurationSource] Error while polling configuration. Try another server if available.: com.ecwid.consul.transport.TransportException: java.net.UnknownHostException: i-40926986.node.usw2.consul.
        at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:80) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:39) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:81) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:150) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:143) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:133) [consul-api-1.1.7.jar:]
        at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:384) [consul-api-1.1.7.jar:]
```

**Comment by Hillkorn** [comment]
Sorry was off the last days. I take a look at it.
The consul servers are discoverable with the http api.

And yes I think it would make sense to only connect to the consul agent and let the logic to get the data from a server done by it instead of duplicate this.

**Comment by Hillkorn** [comment]
Changed it with version 0.2.0

Now consul doesn't fetch the servers and uses by default the https://github.com/Ecwid/consul-api default.
If the server is not available it tries to connect again on the next interval.
